# Configures the documentation build on Read-the-Docs.

version: 2

build:
    os: ubuntu-24.04
    tools:
      python: "3.13"
    jobs:
        pre_install:
          - asdf plugin add uv
          - asdf install uv 0.7.3
          - asdf global uv 0.7.3
        install:
          - uv tool run --from=toml-cli
            toml set --toml-path=pyproject.toml
            project.requires-python ">= 3.13"
          - uv sync --only-group docs
        build:
          html:
            - uv run
              sphinx-build --fail-on-warning
              docs $READTHEDOCS_OUTPUT/html
