# Project meta information

[project]
name = 'MPh'
authors = [{name='John Hennig'}]
version = '1.3.2'
description = 'Pythonic scripting interface for Comsol Multiphysics'
keywords = [
    'Comsol',
    'multiphysics',
    'physics',
    'finite elements',
    'computer simulation',
]
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Topic :: Scientific/Engineering :: Physics',
    'Intended Audience :: Science/Research',
]
license = 'MIT'
license-files = ['license.txt']
readme = 'PyPI.md'

requires-python = '>= 3.10'
dependencies = [
    'JPype1',
    'NumPy',
]

[dependency-groups]
test = [
    'Ruff         >= 0.16',
    'basedPyright >= 1.29',
    'pyTest       >= 8',
    'pyTest-cov   >= 7',
]
docs = [
    'Sphinx      >= 8, < 9',
    'MyST-parser >= 1',
    'Furo        >= 2024',
]
dev = [
    {include-group = 'test'},
    {include-group = 'docs'},
]

[project.urls]
Documentation = 'https://mph.readthedocs.io'
Source        = 'https://github.com/MPh-py/MPh'


# Build backend: UV

[build-system]
requires      = ['uv_build >= 0.9.8, <1']
build-backend = 'uv_build'

[tool.uv.build-backend]
module-name = 'mph'
module-root = '.'


# Code linter: Ruff

[tool.ruff]
line-length    = 79
indent-width   = 4
target-version = 'py310'
include = [
    'mph/*.py',
    'tests/*.py',
    'tools/*.py',
    'demos/*.py',
    'pyproject.toml',
]

    [tool.ruff.format]
    # The project does not actually use the Ruff formatter (only the linter),
    # but these settings would be used if it did.
    quote-style = 'single'
    line-ending = 'cr-lf'

    [tool.ruff.lint]
    preview = true
    select = [
        'F',                  # basic linter rules
        'E',                  # code style errors
        'W',                  # code style warnings
        'B',                  # possible bugs
        'Q',                  # quotation marks
        'ARG',                # unused function arguments
        'C4',                 # correct comprehensions
        'ERA',                # commented-out code
        'FA',                 # future annotations
        'PIE',                # miscellaneous lints
        'PT',                 # pyTest style
        'PTH',                # pathlib use mandatory
        'RSE',                # raised exceptions
        'RUF',                # ruff-specific rules
        'SIM',                # simplifiable code
        'T10',                # debugger calls
        'UP',                 # upgradable code
    ]
    ignore = [
        'whitespace-after-open-bracket',
        'multiple-spaces-before-operator',
        'missing-whitespace-around-arithmetic-operator',
        'missing-whitespace',
        'multiple-spaces-after-comma',
        'unexpected-spaces-around-keyword-parameter-equals',
        'multiple-spaces-before-keyword',
        'assert-raises-exception',
        'no-explicit-stacklevel',
        'unnecessary-comprehension',
        'needless-bool',
        'suppressible-exception',
        'if-else-block-instead-of-if-exp',
        'uncapitalized-environment-variables',
        'pytest-raises-too-broad',
        'pytest-raises-with-multiple-statements',
        'pytest-incorrect-pytest-import',
        'path-constructor-current-directory',
        'implicit-optional',
        'none-not-at-end-of-union',
        'float-equality-comparison',
        'os-error-alias',
    ]
    allowed-confusables = [
        "–",        # n-dash
    ]


    [tool.ruff.lint.per-file-ignores]
    '__init__.py' = [
        'unused-import',
    ]

    [tool.ruff.lint.flake8-quotes]
    inline-quotes    = 'single'
    multiline-quotes = 'double'
    docstring-quotes = 'double'
    avoid-escape     = true


# Type checker: (based)Pyright

[tool.pyright]
include                            = ['mph/', 'tests/']
typeCheckingMode                   = 'standard'
reportUnnecessaryTypeIgnoreComment = true
reportMissingImports               = false
strictParameterNoneValue           = false
reportOptionalMemberAccess         = false
reportAttributeAccessIssue         = false
reportPossiblyUnboundVariable      = false
reportCallIssue                    = false


# Test runner: pyTest

[tool.pytest.ini_options]
addopts              = '--verbose'
testpaths            = ['tests']
console_output_style = 'count'

[tool.coverage.run]
source = ['mph/']
omit   = ['mph/discovery.py']  # Ignore platform-dependent discovery mechanism.
data_file = 'build/coverage/.coverage'
relative_files = true
patch = ['subprocess']

[tool.coverage.report]
exclude_lines = [
    'pragma: no cover',
    'def location',           # Ignore platform-dependent configuration search.
]

[tool.coverage.html]
directory = 'build/coverage'

[tool.coverage.xml]
output = 'build/coverage/coverage.xml'
