"""
MyST-compatible drop-in replacement for Sphinx's Autosummary extension

This extension monkey-patches Autosummary's generation of [domain]
references (roles) so that the syntax is what the MyST Markdown parser
expects, instead of Sphinx's own reStructuredText parser.

Needless to say, this is a hack. Autosummary should be aware of the
the document parser it creates content for, but it's not. That would
require substantial upstream changes.

[domain]: https://www.sphinx-doc.org/en/master/usage/restructuredtext\
/domains.html
"""
__version__ = '0.2.0'


from sphinx.ext import autosummary


class Autosummary(autosummary.Autosummary):
    """Extends the `autosummary` directive provided by Autosummary."""

    def get_table(self, items):
        """
        Monkey-patches the generation of the summary table.

        All we do here is replace each of the `:py:obj:` strings
        generated by Autosummary with the MyST-style directive
        `{py:obj}` if MyST is the document parser.
        """

        # Find out if parser is MyST.
        # The way we do this is a hack. There must be a better way.
        parser_is_myst = self.state.__module__.startswith('myst')

        # Install our parser hook.
        if parser_is_myst:
            myst_parse = self.state.nested_parse

            def shim(block, offset, node, **arguments):
                block.replace(':py:obj:', '{py:obj}')
                myst_parse(block, offset, node, **arguments)

            self.state.nested_parse = shim

        # Let Autosummary do its thing.
        (table_spec, table) = super().get_table(items)

        # Uninstall our hook so we don't mess with anything else.
        if parser_is_myst:
            self.state.nested_parse = myst_parse

        # Return the Autosummary table.
        return [table_spec, table]


def setup(app):
    """
    Sets up the extension.

    Sphinx calls this function if the user named this extension in
    `conf.py`. We then set up the Autosummary extension that ships
    with Sphinx and install our hook to convert Sphinx directives
    to MyST directives.
    """
    app.setup_extension('sphinx.ext.autosummary')
    app.add_directive('autosummary', Autosummary, override=True)
    return {'version': __version__, 'parallel_read_safe': True}
