# Check code quality of latest commit.

on: [push, pull_request, workflow_dispatch]

jobs:

  code:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python:
              - "3.10"
              - "3.11"
              - "3.12"
              - "3.13"
    steps:

      - name: Check out code.
        uses: actions/checkout@v5

      - name: Install Python.
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Install UV.
        uses: astral-sh/setup-uv@v7

      - name: Install package.
        run:  uv sync

      - name: Lint code.
        run:  uv run ruff check

      - name: Check types.
        run:  uv run basedpyright

      - name: Run tests.
        run:  uv run tools/run_tests.py config
        # We only run the very small part of the test suite that doesn't
        # require Comsol to be installed. This essentially just tests that
        # the library can be successfully imported, but not much more.


  docs:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code.
        uses: actions/checkout@v5

      - name: Install Python.
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install UV.
        uses: astral-sh/setup-uv@v7

      - name: Install package.
        run:  uv sync --group docs

      - name: Render documentation.
        run:  uv run sphinx-build --fail-on-warning docs build/docs
