# Publish new GitHub release on PyPI.
name: Publish release

on: [workflow_dispatch]

jobs:

  build:
      runs-on: ubuntu-latest
      steps:

        - name: Check out code.
          uses: actions/checkout@v6

        - name: Install Python.
          uses: actions/setup-python@v6
          with:
            python-version: "3.14"

        - name: Install UV.
          uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d

        - name: Build wheel.
          run:  uv build --wheel --out-dir build/wheel

        - name: Store wheel.
          uses: actions/upload-artifact@v4
          with:
            name: wheel
            path: build/wheel


  publish:
      needs:
        - build
      runs-on: ubuntu-latest
      environment:
          name: pypi
          url:  https://pypi.org/p/MPh
      permissions:
          id-token: write
      steps:

        - name: Download wheel.
          uses: actions/download-artifact@v5
          with:
            name: wheel
            path: build/wheel

        - name: Publish to PyPI.
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            packages-dir: build/wheel
